let numbers = new Array(5, 6, 7, 8, 9, 10)
console.log(numbers)
console.log(numbers[0])
console.log(numbers[1])
console.log(numbers[2])
console.log(numbers[3])
console.log(numbers[4])
console.log(numbers[5])